<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Widget\Taxvat $block */
?>

<div class="field taxvat<?= $block->isRequired() ? ' required' : ''; ?>">

 <div class="form-row">
  <div class="col-lg-8 col-xl-9 form-group font-weight-light">
  
   <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('taxvat')) ?>">
    <span><?= $block->escapeHtml($block->getStoreLabel('taxvat')) ?></span>
   </label>
   
   <div class="control">
    <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('taxvat')) ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName('taxvat')) ?>" value="<?= $block->escapeHtmlAttr($block->getTaxvat()) ?>" title="<?= $block->escapeHtmlAttr($block->getStoreLabel('taxvat')) ?>" class="form-control input-text <?= $block->escapeHtmlAttr($this->helper(\Magento\Customer\Helper\Address::class)->getAttributeValidationClass('taxvat')) ?>" <?= $block->isRequired() ? ' data-validate="{required:true}"' : '' ?>>
   </div>
   
  </div>
 </div>

</div>
