<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Vault\Block\Customer\CreditCards $block */
$tokens = $block->getPaymentTokens();
?>

<?php if (count($tokens) !== 0) : ?>
<div class="table-responsive table-wrapper my-credit-cards">
 <table class="table-bordered data table table-credit-cards" id="my-orders-table">
  <thead>
   <tr>
    <th scope="col" class="font-weight-normal card-number"><?= $block->escapeHtml(__('Card Number')) ?></th>
    <th scope="col" class="font-weight-normal expire"><?= $block->escapeHtml(__('Expiration Date')) ?></th>
    <th scope="col" class="font-weight-normal card-type"><?= $block->escapeHtml(__('Type')) ?></th>
    <th scope="col" class="font-weight-normal actions">&nbsp;</th>
   </tr>
  </thead>
  <tbody>
  <?php
   foreach ($tokens as $token) {
    echo $block->renderTokenHtml($token);
   }
  ?>
  </tbody>
 </table>
</div>

<?php elseif (!$block->isExistsCustomerTokens()) : ?>
<div class="alert alert-warning font-weight-light rounded-0 mb-3 message info empty" role="alert">
 <span><?= $block->escapeHtml(__('You have no stored payment methods.')) ?></span>
</div>
<?php endif ?>
