<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Sidebar $block */
?>
<?php

$wishlistHelper = $this->helper(\Magento\Wishlist\Helper\Data::class);

?>

<?php if ($wishlistHelper->isAllow()) : ?>
<div class="block block-wishlist" data-bind="scope: 'wishlist'">

 <h2 role="heading" aria-level="2" class="block-title font-weight-light h5 mb-4">
  <span aria-level="2"><?= $block->escapeHtml($block->getTitle()) ?></span>
  <!-- ko if: wishlist().counter -->
  <span data-bind="text: '(' + wishlist().counter + ')'" class="counter"></span>
  <!-- /ko -->
 </h2>

 <div class="block-content">

  <span class="subtitle d-none"><?= $block->escapeHtml(__('Last Added Items')) ?></span>
 
  <!-- ko if: wishlist().counter -->
  <ol class="product-items list-unstyled d-none" id="wishlist-sidebar" data-bind="foreach: wishlist().items, css: {'d-none': null}">
   <li class="product-item">
  
    <div class="product-item-info row mb-3">

     <div class="col-auto">
      <a class="product-item-photo d-block" data-bind="attr: { href: product_url, title: product_name }">
      <!-- ko template: {name: $data.image.template, data: $data.image} --><!-- /ko -->
      </a>
     </div>
    
     <div class="product-item-details col">

      <div class="d-flex">

       <div class="mr-2">
       
        <span class="product-item-name">
         <a data-bind="attr: { href: product_url }" class="product-item-link text-dark font-weight-light mb-1">
          <span data-bind="html: product_name"></span>
         </a>
        </span>
        
        <div data-bind="html: product_price"></div>
        
        <!-- ko if: product_is_saleable_and_visible -->
        <div class="actions-primary">
        
         <!-- ko if: product_has_required_options -->
         <a href="#" data-bind="attr: {'data-post': add_to_cart_params}" class="action tocart primary btn btn-primary rounded-0 font-weight-light">
          <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
         </a>
         <!-- /ko -->
         
         <!-- ko ifnot: product_has_required_options -->
         <button type="button" class="action tocart primary btn btn-primary rounded-0 font-weight-light" data-bind="attr: {'data-post': add_to_cart_params}">
          <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
         </button>
         <!-- /ko -->
         
        </div>
        <!-- /ko -->

       </div>

       <div class="actions-secondary ml-auto">
        <a href="#" data-bind="attr: {'data-post': delete_item_params}" title="<?= $block->escapeHtmlAttr(__('Remove')) ?>" class="btn-remove action delete text-dark font-weight-light">
         <span class="d-none"><?= $block->escapeHtml(__('Remove')) ?></span>
         <i class="fas fa-times"></i>
        </a>
       </div>

      </div>

     </div>
    
    </div>
   
   </li>
  </ol>
 
  <div class="actions-toolbar d-none" data-bind="css: {'d-none': null}">

   <div class="primary">
    <a class="d-inline-block font-weight-light mb-2 details" href="<?= $block->escapeUrl($this->helper(\Magento\Wishlist\Helper\Data::class)->getListUrl()) ?>" title="<?= $block->escapeHtmlAttr(__('Go to Wish List')) ?>">
     <span><?= $block->escapeHtml(__('Go to Wish List')) ?></span>
    </a>
   </div>
  
  </div>
  <!-- /ko -->
 
  <!-- ko ifnot: wishlist().counter -->
  <div class="font-weight-light mb-4 empty">
   <?= $block->escapeHtml(__('You have no items in your wish list.')) ?>
  </div>
  <!-- /ko -->
 
 </div>
 
</div>

<script type="text/x-magento-init">
 {
  "*": {
   "Magento_Ui/js/core/app": {
    "components": {
     "wishlist": {
      "component": "Magento_Wishlist/js/view/wishlist"
     }
    }
   }
  }
 }
</script>

<?php endif ?>
