<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-amount my-3" id="toolbar-amount">

 <?php if ($block->getLastPageNum() > 1) :?>
 
  <?= $block->escapeHtml(
    __(
     'Items: %1-%2 of %3',
     '<span class="font-weight-light toolbar-number">' . $block->getFirstNum() . '</span>',
     '<span class="font-weight-light toolbar-number">' . $block->getLastNum() . '</span>',
     '<span class="font-weight-light toolbar-number">' . $block->getTotalNum() . '</span>'
    ),
    ['span']
  ) ?>
  
 <?php elseif ($block->getTotalNum() == 1) :?>
 
  <?= $block->escapeHtml(
    __('%1 Item', '<span class="font-weight-light toolbar-number">' . $block->getTotalNum() . '</span>'),
     ['span']
    ) ?>
    
 <?php else :?>
  
   <?= $block->escapeHtml(
    __('%1 Items', '<span class="font-weight-light toolbar-number">' . $block->getTotalNum() . '</span>'),
    ['span']
   ) ?>
   
 <?php endif; ?>

</div>
