<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="my-4 field limiter">

 <label class="label" for="limiter">
  <?= $block->escapeHtml(__('Show:')) ?>
 </label>
 
 <div class="d-inline-block mx-2">
  <select id="limiter" data-role="limiter" class="form-control font-weight-light p-1 limiter-options">
   <?php foreach ($block->getAvailableLimit() as $_key => $_limit) :?>
   <option value="<?= $block->escapeHtmlAttr($_key) ?>" <?php if ($block->isLimitCurrent($_key)) :?> selected="selected" <?php endif ?>>
    <?= $block->escapeHtml($_limit) ?>
   </option>
   <?php endforeach; ?>
  </select>
 </div>
 
 <span class="font-weight-light limiter-text">
  <?= $block->escapeHtml(__('per page')) ?>
 </span>

</div>
