<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter my-3">

 <label class="sorter-label mb-0" for="sorter">
  <?= $block->escapeHtml(__('Sort By:')) ?>
 </label>

 <div class="d-inline-block mx-2">
  <select id="sorter" data-role="sorter" class="sorter-options h-100 form-control font-weight-light p-1">
   <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
   <option value="<?= $block->escapeHtmlAttr($_key) ?>" <?php if ($block->isOrderCurrent($_key)) :?>  selected="selected" <?php endif; ?>>
    <?= $block->escapeHtml(__($_order)) ?>
   </option>
   <?php endforeach; ?>
  </select>
 </div>
 
 <?php if ($block->getCurrentDirection() == 'desc') :?>
 <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>" href="#" class="sorter-action sort-desc text-dark text-decoration-none" data-role="direction-switcher" data-value="asc">
  <span class="text-hide d-none"><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
  <i class="fas fa-arrow-up"></i>
 </a>
 <?php else :?>
 <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>" href="#" class="sorter-action sort-asc text-dark text-decoration-none" data-role="direction-switcher" data-value="desc">
  <span class="text-hide d-none"><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
  <i class="fas fa-arrow-down"></i>
 </a>
 <?php endif; ?>

</div>
