<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>

<?php if ($block->isEnabledViewSwitcher()) :?>
<div class="modes my-3">

 <?php $_modes = $block->getModes(); ?>
 
 <?php if ($_modes && count($_modes) > 1) :?>

 <span class="text-hide modes-label" id="modes-label">
  <?= $block->escapeHtml(__('View as:')) ?>
 </span>
 
 <?php foreach ($block->getModes() as $_code => $_label) :?>
 
  <?php if ($block->isModeActive($_code)) :?>

  <span title="<?= $block->escapeHtmlAttr($_label) ?>" class="mx-1 bg-light d-inline-block border px-2 py-1 modes-mode active mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>" data-value="<?= $block->escapeHtmlAttr(strtolower($_code)) ?>">
   <span class="text-hide d-none"><?= $block->escapeHtml($_label) ?></span>
   <?php if($block->escapeHtml($_label) == 'Grid') : ?>
    <i class="fas fa-th"></i>
   <?php else : ?>
    <i class="fas fa-th-list"></i>
   <?php endif; ?>
  </span>
  
  <?php else :?>

  <a class="text-dark text-decoration-none mx-1 d-inline-block border px-2 py-1 modes-mode mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>" title="<?= $block->escapeHtmlAttr($_label) ?>" href="#" data-role="mode-switcher" data-value="<?= $block->escapeHtmlAttr(strtolower($_code)) ?>" id="mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>" aria-labelledby="modes-label mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>">
   <span class="text-hide d-none"><?= $block->escapeHtml($_label) ?></span>
   <?php if($block->escapeHtml($_label) == 'Grid') : ?>
    <i class="fas fa-th"></i>
   <?php else : ?>
    <i class="fas fa-th-list"></i>
   <?php endif; ?>
  </a>

  <?php endif; ?>
  
 <?php endforeach; ?>
 
 <?php endif; ?>
 
</div>
<?php endif; ?>
