<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Address\Book $block */
?>
<div class="block block-addresses-default mb-4">

 <h2 role="heading" aria-level="2" class="block-title font-weight-light h5 mb-4 pb-3 border-bottom">
  <span><?= $block->escapeHtml(__('Default Addresses')) ?></span>
 </h2>
 
 <div class="block-content row">
 
  <?php if ($_pAddsses = $block->getDefaultBilling()) : ?>
  <div class="box box-address-billing col-md-6">

   <h3 class="box-title font-weight-normal h6">
    <span><?= $block->escapeHtml(__('Default Billing Address')) ?></span>
   </h3>
   
   <div class="box-content font-weight-light mb-2">
    <address>
    <?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
    </address>
   </div>
   
   <div class="box-actions mb-3">
    <a class="action edit font-weight-light" href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>">
     <span><?= $block->escapeHtml(__('Change Billing Address')) ?></span>
    </a>
   </div>
   
  </div>
  
  <?php else : ?>
  <div class="box box-billing-address col-md-6">

   <h3 class="box-title font-weight-normal h6">
    <span><?= $block->escapeHtml(__('Default Billing Address')) ?></span>
   </h3>
   
   <div class="box-content font-weight-normal mb-3">
    <p><?= $block->escapeHtml(__('You have no default billing address in your address book.')) ?></p>
   </div>

  </div>
  <?php endif ?>
  
  <?php if ($_pAddsses = $block->getDefaultShipping()) : ?>
  <div class="box box-address-shipping col-md-6">

   <h3 class="box-title font-weight-normal h6">
    <span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span>
   </h3>
   
   <div class="box-content font-weight-light mb-2">
    <address>
    <?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
    </address>
   </div>
   
   <div class="box-actions mb-3">
    <a class="action edit font-weight-light" href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>">
     <span><?= $block->escapeHtml(__('Change Shipping Address')) ?></span>
    </a>
   </div>

  </div>
  <?php else : ?>
  <div class="box box-shipping-address col-md-6">
  
   <h3 class="box-title font-weight-normal h6">
    <span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span>
   </h3>
   
   <div class="box-content font-weight-normal mb-3">
    <p><?= $block->escapeHtml(__('You have no default shipping address in your address book.')) ?></p>
   </div>
   
  </div>
  <?php endif ?>
  
 </div>
</div>
