<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Customer\ListCustomer $block */
?>
<?php if ($block->getReviews() && count($block->getReviews())) : ?>
<div class="table-wrapper reviews table-responsive">
 <table class="data table table-reviews table-bordered" id="my-reviews-table">

  <caption class="table-caption text-hide"><?= $block->escapeHtml(__('Product Reviews')) ?></caption>

  <thead>
   <tr>
    <th scope="col" class="date font-weight-normal"><?= $block->escapeHtml(__('Created')) ?></th>
    <th scope="col" class="item font-weight-normal"><?= $block->escapeHtml(__('Product Name')) ?></th>
    <th scope="col" class="summary font-weight-normal"><?= $block->escapeHtml(__('Rating')) ?></th>
    <th scope="col" class="description font-weight-normal"><?= $block->escapeHtml(__('Review')) ?></th>
    <th scope="col" class="actions font-weight-normal">&nbsp;</th>
   </tr>
  </thead>
  
  <tbody>
  
   <?php foreach ($block->getReviews() as $review) : ?>
   <tr>
    <td data-th="<?= $block->escapeHtmlAttr(__('Created')) ?>" class="date font-weight-light">
     <?= $block->escapeHtml($block->dateFormat($review->getReviewCreatedAt())) ?>
    </td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Product Name')) ?>" class="item font-weight-light">
     <span class="product-name">
      <a href="<?= $block->escapeUrl($block->getProductUrl($review)) ?>"><?= $block->escapeHtml($review->getName()) ?></a>
     </span>
    </td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Rating')) ?>" class="summary font-weight-light">
     <?php if ($review->getSum()) : ?>
     <div class="rating-summary">
      <span class="label">
       <span><?= $block->escapeHtml(__('Rating')) ?>:</span>
      </span>
      <div class="rating-result" title="<?= /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) ?>%">
       <span style="width:<?= /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) ?>%;">
        <span><?= /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) ?>%</span>
       </span>
      </div>
     </div>
     <?php endif; ?>
    </td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Review')) ?>" class="description font-weight-light">
     <?php //phpcs:disable ?>
     <?= $this->helper(\Magento\Review\Helper\Data::class)->getDetailHtml($review->getDetail()) ?>
     <?php //phpcs:enable ?>
    </td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="actions font-weight-light">
     <a href="<?= $block->escapeUrl($block->getReviewUrl($review)) ?>" class="action more">
      <span><?= $block->escapeHtml(__('See Details')) ?></span>
     </a>
    </td>
   </tr>
   <?php endforeach; ?>
   
  </tbody>
 </table>
</div>
<?php if ($block->getToolbarHtml()) : ?>
<div class="toolbar products-reviews-toolbar bottom">
 <?= $block->getToolbarHtml() ?>
</div>
<?php endif; ?>
<?php else : ?>
<div class="message info empty alert alert-warning font-weight-light rounded-0 mb-3" role="alert">
 <span><?= $block->escapeHtml(__('You have submitted no reviews.')) ?></span>
</div>
<?php endif; ?>
<div class="actions-toolbar">
 <div class="secondary">
  <a class="action back text-dark font-weight-light" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
   <span><?= $block->escapeHtml(__('Back')) ?></span>
  </a>
 </div>
</div>
