<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
?>
<?php if ($block->isWishListAllowed()) : ?>
<a href="#" class="action towishlist text-uppercase text-dark mr-3" data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>' data-action="add-to-wishlist">
 <i class="fas fa-heart"></i>
 <span class="font-weight-normal"><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
</a>
<?php endif; ?>

<script type="text/x-magento-init">
 {
  "body": {
   "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
  }
}
</script>
