<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * @var $block \Magento\Downloadable\Block\Customer\Products\ListProducts
 */
?>

<?php $_items = $block->getItems(); ?>

<?php if (count($_items)) : ?>
<div class="table-responsive table-wrapper downloadable-products">

 <table id="my-downloadable-products-table" class="table-bordered data table table-downloadable-products">

  <thead>
   <tr>
    <th scope="col" class="font-weight-normal id"><?= $block->escapeHtml(__('Order #')) ?></th>
    <th scope="col" class="font-weight-normal date"><?= $block->escapeHtml(__('Date')) ?></th>
    <th scope="col" class="font-weight-normal title"><?= $block->escapeHtml(__('Title')) ?></th>
    <th scope="col" class="font-weight-normal status"><?= $block->escapeHtml(__('Status')) ?></th>
    <th scope="col" class="font-weight-normal remaining"><?= $block->escapeHtml(__('Remaining Downloads')) ?></th>
   </tr>
  </thead>
  
  <tbody>
   <?php foreach ($_items as $_item) : ?>
   <tr>
    <td data-th="<?= $block->escapeHtmlAttr(__('Order #')) ?>" class="font-weight-light id">
     <a href="<?= $block->escapeUrl($block->getOrderViewUrl($_item->getPurchased()->getOrderId())) ?>" title="<?= $block->escapeHtmlAttr(__('View Order')) ?>">
      <?= $block->escapeHtml($_item->getPurchased()->getOrderIncrementId()) ?>
     </a>
    </td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="font-weight-light date">
     <?= $block->escapeHtml($block->formatDate($_item->getPurchased()->getCreatedAt())) ?>
    </td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Title')) ?>" class="font-weight-light title">
     <strong class="product-name"><?= $block->escapeHtml($_item->getPurchased()->getProductName()) ?></strong>
     <?php if ($_item->getStatus() == \Magento\Downloadable\Model\Link\Purchased\Item::LINK_STATUS_AVAILABLE) : ?>
     <a href="<?= $block->escapeUrl($block->getDownloadUrl($_item)) ?>" title="<?= $block->escapeHtmlAttr(__('Start Download')) ?>" class="action download" <?= /* @noEscape */ $block->getIsOpenInNewWindow() ? 'onclick="this.target=\'_blank\'"' : '' ?>>
      <?= $block->escapeHtml($_item->getLinkTitle()) ?>
     </a>
     <?php endif; ?>
    </td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>" class="font-weight-light status">
     <?= $block->escapeHtml(__(ucfirst($_item->getStatus()))) ?>
    </td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Remaining Downloads')) ?>" class="font-weight-light remaining">
     <?= $block->escapeHtml($block->getRemainingDownloads($_item)) ?>
    </td>
   </tr>
   <?php endforeach; ?>
  </tbody>
  
 </table>

</div>

 <?php if ($block->getChildHtml('pager')) : ?>
 <div class="toolbar downloadable-products-toolbar bottom">
 <?= $block->getChildHtml('pager') ?>
 </div>
 <?php endif; ?>
 
<?php else : ?>
 <div class="font-weight-light mb-3 message info empty">
  <span><?= $block->escapeHtml(__('You have not purchased any downloadable products yet.')) ?></span>
 </div>
<?php endif; ?>

<div class="actions-toolbar">
 <div class="secondary">
  <a href="<?= $block->escapeUrl($block->getBackUrl()) ?>" class="font-weight-light action back">
   <span><?= $block->escapeHtml(__('Back')) ?></span>
  </a>
 </div>
</div>
