<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\Wishlist\Block\Customer\Wishlist\Items $block */
$columns = $block->getColumns();
?>

<div class="products-grid wishlist">

 <?php if (count($block->getItems())) : ?>
 <ol class="product-items row list-unstyled">
 
  <?php foreach ($block->getItems() as $item) : ?>
  <li data-row="product-item" class="product-item col-6 col-md-4 pb-4" id="item_<?= $block->escapeHtmlAttr($item->getId()) ?>">
   <div class="product-item-info" data-container="product-grid">
    <?php foreach ($columns as $column) : ?>
    <?= $column->setItem($item)->toHtml();?>
    <?php endforeach; ?>
   </div>
  </li>
  <?php endforeach; ?>
  
 </ol>
 <?php else : ?>
 <div class="message info empty alert alert-warning font-weight-light rounded-0 mb-3" role="alert">
  <span><?= $block->escapeHtml(__('This Wish List has no Items')) ?></span>
 </div>
 <?php endif; ?>
 
</div>

<?php foreach ($columns as $column) : ?>
 <?= $column->getAdditionalHtml() ?>
<?php endforeach; ?>
