<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php /** @var $block \Magento\Framework\Pricing\Render\Amount */ ?>

<div class="price-container <?= $block->escapeHtmlAttr($block->getAdjustmentCssClasses()) ?> d-block mb-3" <?= $block->getSchema() ? ' itemprop="offers" itemscope itemtype="http://schema.org/Offer"' : '' ?>>

 <?php if ($block->getDisplayLabel()) :?>
 <div class="price-label font-weight-light mb-1"><?= $block->escapeHtml($block->getDisplayLabel()) ?></div>
 <?php endif; ?>
 
 <div <?php if ($block->getPriceId()) :?> id="<?= $block->escapeHtmlAttr($block->getPriceId()) ?>"<?php endif;?> <?= ($block->getPriceDisplayLabel()) ? 'data-label="' . $block->escapeHtmlAttr($block->getPriceDisplayLabel() . $block->getPriceDisplayInclExclTaxes()) . '"' : '' ?> data-price-amount="<?= $block->escapeHtmlAttr($block->getDisplayValue()) ?>" data-price-type="<?= $block->escapeHtmlAttr($block->getPriceType()) ?>" class="price-wrapper font-weight-bold <?= $block->escapeHtmlAttr($block->getPriceWrapperCss()) ?>">
  <?= $block->escapeHtml($block->formatCurrency($block->getDisplayValue(), (bool)$block->getIncludeContainer()), ['span']) ?>
 </div>
 
 <?php if ($block->hasAdjustmentsHtml()) :?>
  <?= $block->getAdjustmentsHtml() ?>
 <?php endif; ?>
 
 <?php if ($block->getSchema()) :?>
 <meta itemprop="price" content="<?= $block->escapeHtmlAttr($block->getDisplayValue()) ?>" />
 <meta itemprop="priceCurrency" content="<?= $block->escapeHtmlAttr($block->getDisplayCurrencyCode()) ?>" />
 <?php endif; ?>

</div>