<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Framework\View\Element\Html\Link
 */
?>
<?php if (!$block->getIsDisabled()) : ?>
<li class="nav-item">
 <a href="<?= $block->escapeUrl($block->getHref()) ?>" <?php if ($title = $block->getTitle()) : ?> title="<?= $block->escapeHtmlAttr(__($title)) ?>"<?php endif;?> class="nav-link font-weight-light">
  <?= $block->escapeHtml(__($block->getLabel())) ?>
 </a>
</li>
<?php endif; ?>
