<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div data-bind="scope: 'messages'">

 <!-- ko if: cookieMessages && cookieMessages.length > 0 -->
 <div role="alert" data-bind="foreach: { data: cookieMessages, as: 'message' }" class="messages">
   
  <!-- ko if: message.type == 'success' -->
  <div data-bind="attr: {
    class: 'message-' + message.type + ' ' + message.type + ' message ' + ' alert ' + 'alert-success rounded-0 px-3 py-2',
    'data-ui-id': 'message-' + message.type
  }">
   <div data-bind="html: message.text"></div>
  </div>
  <!-- /ko -->

  <!-- ko if: message.type == 'notice' -->
  <div data-bind="attr: {
    class: 'message-' + message.type + ' ' + message.type + ' message ' + ' alert ' + 'alert-warning rounded-0 px-3 py-2',
    'data-ui-id': 'message-' + message.type
  }">
   <div data-bind="html: message.text" class="d-inline-block"></div>
  </div>
  <!-- /ko -->

  <!-- ko if: message.type == 'error' -->
  <div data-bind="attr: {
    class: 'message-' + message.type + ' ' + message.type + ' message ' + ' alert ' + 'alert-danger rounded-0 px-3 py-2',
    'data-ui-id': 'message-' + message.type
  }">
   <div data-bind="html: message.text" class="d-inline-block"></div>
  </div>
  <!-- /ko -->
 
 </div>
 <!-- /ko -->
 
 <!-- ko if: messages().messages && messages().messages.length > 0 -->
 <div role="alert" data-bind="foreach: { data: messages().messages, as: 'message' }" class="messages">

  <!-- ko if: message.type == 'success' -->
  <div data-bind="attr: {
    class: 'message-' + message.type + ' ' + message.type + ' message ' + ' alert ' + 'alert-success rounded-0 px-3 py-2',
    'data-ui-id': 'message-' + message.type
  }">
   <div data-bind="html: message.text"></div>
  </div>
  <!-- /ko -->

  <!-- ko if: message.type == 'notice' -->
  <div data-bind="attr: {
    class: 'message-' + message.type + ' ' + message.type + ' message ' + ' alert ' + 'alert-warning rounded-0 px-3 py-2',
    'data-ui-id': 'message-' + message.type
  }">
   <div data-bind="html: message.text" class="d-inline-block"></div>
  </div>
  <!-- /ko -->

  <!-- ko if: message.type == 'error' -->
  <div data-bind="attr: {
    class: 'message-' + message.type + ' ' + message.type + ' message ' + ' alert ' + 'alert-danger rounded-0 px-3 py-2',
    'data-ui-id': 'message-' + message.type
  }">
   <div data-bind="html: message.text" class="d-inline-block"></div>
  </div>
  <!-- /ko -->

 </div>
 <!-- /ko -->
 
</div>

<script type="text/x-magento-init">
 {
  "*": {
   "Magento_Ui/js/core/app": {
    "components": {
     "messages": {
      "component": "Magento_Theme/js/view/messages"
     }
    }
   }
  }
 }
</script>
