<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<!doctype html>
<html <?= /* @noEscape */ $htmlAttributes ?> class="h-100">
 <head <?= /* @noEscape */ $headAttributes ?>>
  <?= /* @noEscape */ $requireJs ?>
  <?= /* @noEscape */ $headContent ?>
  <?= /* @noEscape */ $headAdditional ?>
 </head>
 <body data-container="body" class="h-100" data-mage-init='{"loaderAjax": {}, "loader": { "icon": "<?= /* @noEscape */ $loaderIcon ?>"}}' <?= /* @noEscape */ $bodyAttributes ?>>
  <?= /* @noEscape */ $layoutContent ?> 
 </body>
</html>
