<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Form $block */
?>

<div class="review-add">

 <h2 role="heading" class="font-weight-light h5 mb-3 review-add-title">
  <span><?= $block->escapeHtml(__('Write Your Own Review')) ?></span>
 </h2>
 
 <div class="review-add-content">
 
  <?php if ($block->getAllowWriteReviewFlag()) : ?>
  <form action="<?= $block->escapeUrl($block->getAction()) ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
  
   <?= $block->getBlockHtml('formkey') ?>
   <?= $block->getChildHtml('form_fields_before') ?>
   
   <fieldset class="fieldset review-fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">

    <legend class="font-weight-light d-none legend review-legend">
     <span><?= $block->escapeHtml(__("You're reviewing:")) ?></span>
     <strong><?= $block->escapeHtml($block->getProductInfo()->getName()) ?></strong>
    </legend>
    
    <?php if ($block->getRatings() && $block->getRatings()->getSize()) : ?>
    <div class="form-row">

     <div class="col-md-8 col-lg-6">

      <span id="input-message-box"></span>

      <fieldset class="form-group field required review-field-ratings">
      
       <legend class="font-weight-light d-none label">
        <span><?= $block->escapeHtml(__('Your Rating')) ?></span>
       </legend>
       
       <div class="control">
        <div class="nested" id="product-review-table">
         <?php foreach ($block->getRatings() as $_rating) : ?>
         <div class="field choice review-field-rating">
          <label class="label" id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_rating_label">
           <span><?= $block->escapeHtml($_rating->getRatingCode()) ?></span>
          </label>
          <div class="control review-control-vote">
          
           <?php $options = $_rating->getOptions();?>
           <?php $iterator = 1; foreach ($options as $_option) : ?>
           <input type="radio" name="ratings[<?= $block->escapeHtmlAttr($_rating->getId()) ?>]" id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>" value="<?= $block->escapeHtmlAttr($_option->getId()) ?>" class="radio" data-validate="{'rating-required':true}" aria-labelledby="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_rating_label <?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label" />
           <label class="rating-<?= $block->escapeHtmlAttr($iterator) ?>" for="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>" title="<?= $block->escapeHtmlAttr(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?>" id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label">
            <span><?= $block->escapeHtml(__('%1 %2', $iterator, $iterator > 1 ? __('stars') : __('star'))) ?></span>
           </label>
           <?php $iterator++; ?>
           <?php endforeach; ?>

          </div>
         </div>
         <?php endforeach; ?>
        </div>
        <input type="hidden" name="validate_rating" class="validate-rating" value="" />
       </div>
       
      </fieldset>
     
     </div>
    </div>
    <?php endif ?>

    <div class="form-row">
     <div class="col-md-8 col-lg-6">

      <div class="form-group field review-field-nickname required">
       <label for="nickname_field" class="d-block label">
        <span><?= $block->escapeHtml(__('Nickname')) ?></span>
       </label>
       <input type="text" name="nickname" id="nickname_field" class="form-control input-text" data-validate="{required:true}" data-bind="value: nickname()" />
      </div>
      
      <div class="form-group field review-field-summary required">
       <label for="summary_field" class="d-block label">
        <span><?= $block->escapeHtml(__('Summary')) ?></span>
       </label>
       <input type="text" name="title" id="summary_field" class="form-control input-text" data-validate="{required:true}" data-bind="value: review().title" />
      </div>

      <div class="form-group field review-field-text required">
       <label for="review_field" class="d-block label">
        <span><?= $block->escapeHtml(__('Review')) ?></span>
       </label>
       <textarea name="detail" class="form-control" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
      </div>
     
     </div>
    </div>

    <div class="form-group actions-toolbar review-form-actions">
     <div class="primary actions-primary">
      <button type="submit" class="btn btn-secondary action submit primary">
       <span><?= $block->escapeHtml(__('Submit Review')) ?></span>
      </button>
     </div>
    </div>
    
   </fieldset>
   
  </form>
  
  <script type="text/x-magento-init">
   {
    "[data-role=product-review-form]": {
     "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    },
    "#review-form": {
     "Magento_Review/js/error-placement": {},
     "Magento_Review/js/validate-review": {}
    }
   }
  </script>
  
  <?php else : ?>
  <div class="message info notlogged" id="review-form">
   <div class="font-weight-light">
    <?= $block->escapeHtml(__('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()), ['a']) ?>
   </div>
  </div>
  <?php endif ?>
  
 </div>
</div>
