<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>

<?php if ($_orders && count($_orders)) : ?>
<div class="table-wrapper orders-history table-responsive">

 <table class="data table table-order-items history table-bordered" id="my-orders-table">

  <caption class="table-caption text-hide"><?= $block->escapeHtml(__('Orders')) ?></caption>

  <thead>
   <tr>
    <th scope="col" class="id font-weight-normal"><?= $block->escapeHtml(__('Order #')) ?></th>
    <th scope="col" class="date font-weight-normal"><?= $block->escapeHtml(__('Date')) ?></th>
    <?= $block->getChildHtml('extra.column.header') ?>
    <th scope="col" class="shipping font-weight-normal"><?= $block->escapeHtml(__('Ship To')) ?></th>
    <th scope="col" class="total font-weight-normal"><?= $block->escapeHtml(__('Order Total')) ?></th>
    <th scope="col" class="status font-weight-normal"><?= $block->escapeHtml(__('Status')) ?></th>
    <th scope="col" class="actions font-weight-normal"><?= $block->escapeHtml(__('Action')) ?></th>
   </tr>
  </thead>
  
  <tbody>
   <?php foreach ($_orders as $_order) : ?>
   <tr>
    <td data-th="<?= $block->escapeHtmlAttr(__('Order #')) ?>" class="id font-weight-light"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="date font-weight-light"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
    <?php $extra = $block->getChildBlock('extra.container'); ?>
    <?php if ($extra) : ?>
     <?php $extra->setOrder($_order); ?>
     <?= $extra->getChildHtml() ?>
    <?php endif; ?>
    <td data-th="<?= $block->escapeHtmlAttr(__('Ship To')) ?>" class="shipping font-weight-light"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Order Total')) ?>" class="total font-weight-light"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>" class="status font-weight-light"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
    <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="actions font-weight-light">
     <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
      <span><?= $block->escapeHtml(__('View Order')) ?></span>
     </a>
     <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
     <a href="#" data-post='<?= /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order))?>' class="ml-2 action order">
      <span><?= $block->escapeHtml(__('Reorder')) ?></span>
     </a>
     <?php endif ?>
    </td>
   </tr>
   <?php endforeach; ?>
  </tbody>
  
 </table>
</div>

 <?php if ($block->getPagerHtml()) : ?>
 <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
 <?php endif ?>

<?php else : ?>
<div class="message info empty alert alert-warning font-weight-light rounded-0 mb-3" role="alert">
 <span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span>
</div>
<?php endif ?>
