<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Recent */
?>
<div class="block block-dashboard-orders">

<?php
 $_orders = $block->getOrders();
 $count = count($_orders);
?>

 <h2 role="heading" aria-level="2" class="block-title order font-weight-light h4 mb-4 pb-3 border-bottom">
  <span><?= $block->escapeHtml(__('Recent Orders')) ?></span>
  <?php if ($count > 0) : ?>
  <a class="action view font-weight-light h6 ml-2" href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>">
   <span><?= $block->escapeHtml(__('View All')) ?></span>
  </a>
  <?php endif; ?>
 </h2>
 
 <div class="block-content">
 
  <?= $block->getChildHtml() ?>
  
  <?php if ($count > 0) : ?>
  <div class="table-wrapper orders-recent table-responsive">

   <table class="data table table-order-items recent table-bordered" id="my-orders-table">

    <thead>
     <tr>
      <th scope="col" class="id font-weight-normal"><?= $block->escapeHtml(__('Order #')) ?></th>
      <th scope="col" class="date font-weight-normal"><?= $block->escapeHtml(__('Date')) ?></th>
      <th scope="col" class="shipping font-weight-normal"><?= $block->escapeHtml(__('Ship To')) ?></th>
      <th scope="col" class="total font-weight-normal"><?= $block->escapeHtml(__('Order Total')) ?></th>
      <th scope="col" class="status font-weight-normal"><?= $block->escapeHtml(__('Status')) ?></th>
      <th scope="col" class="actions font-weight-normal"><?= $block->escapeHtml(__('Action')) ?></th>
     </tr>
    </thead>
    
    <tbody>
     <?php foreach ($_orders as $_order) : ?>
     <tr>
      <td data-th="<?= $block->escapeHtmlAttr(__('Order #')) ?>" class="id font-weight-light"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
      <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="date font-weight-light"><?= $block->escapeHtml($block->formatDate($_order->getCreatedAt())) ?></td>
      <td data-th="<?= $block->escapeHtmlAttr(__('Ship To')) ?>" class="shipping font-weight-light"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : "&nbsp;" ?></td>
      <td data-th="<?= $block->escapeHtmlAttr(__('Order Total')) ?>" class="total font-weight-light"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
      <td data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>" class="status font-weight-light"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
      <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="actions font-weight-light">
       <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
        <span><?= $block->escapeHtml(__('View Order')) ?></span>
       </a>
       <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
       <a href="#" data-post='<?= /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order))?>' class="action order ml-2">
        <span><?= $block->escapeHtml(__('Reorder')) ?></span>
       </a>
       <?php endif ?>
      </td>
     </tr>
     <?php endforeach; ?>
    </tbody>
    
   </table>
   
  </div>
  
  <?php else : ?>
  <div class="message info empty alert alert-warning font-weight-light rounded-0 mb-3" role="alert">
   <span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span>
  </div>
  <?php endif; ?>
  
 </div>
</div>
