<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var $block \Magento\Sales\Block\Order\Recent */
?>
<div class="dashboard-orders">

<?php
 $_orders = $block->getOrders();
 $count = count($_orders);
?>


 <h2 role="heading" aria-level="2" class="font-weight-light h5 mb-4 pb-3 border-bottom title order">
  <span><?= $block->escapeHtml(__('Recent Orders')) ?></span>
  <?php if ($count > 0) : ?>
  <a class="font-weight-light h6 ml-2 action view" href="<?= $block->escapeUrl($block->getUrl('sales/order/history')) ?>">
   <span><?= $block->escapeHtml(__('View All')) ?></span>
  </a>
  <?php endif; ?>
 </h2>
 
 <div class="content">
 
  <?= $block->getChildHtml() ?>
  
  <?php if ($count > 0) : ?>
  <div class="table-responsive table-wrapper orders-recent">

   <table class="table-bordered data table table-order-items recent" id="my-orders-table">

    <thead>
     <tr>
      <th scope="col" class="font-weight-normal id"><?= $block->escapeHtml(__('Order #')) ?></th>
      <th scope="col" class="font-weight-normal date"><?= $block->escapeHtml(__('Date')) ?></th>
      <th scope="col" class="font-weight-normal shipping"><?= $block->escapeHtml(__('Ship To')) ?></th>
      <th scope="col" class="font-weight-normal total"><?= $block->escapeHtml(__('Order Total')) ?></th>
      <th scope="col" class="font-weight-normal status"><?= $block->escapeHtml(__('Status')) ?></th>
      <th scope="col" class="font-weight-normal actions"><?= $block->escapeHtml(__('Action')) ?></th>
     </tr>
    </thead>
    
    <tbody>
     <?php foreach ($_orders as $_order) : ?>
     <tr>
      <td data-th="<?= $block->escapeHtmlAttr(__('Order #')) ?>" class="font-weight-light id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
      <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="font-weight-light date"><?= $block->escapeHtml($block->formatDate($_order->getCreatedAt())) ?></td>
      <td data-th="<?= $block->escapeHtmlAttr(__('Ship To')) ?>" class="font-weight-light shipping"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : "&nbsp;" ?></td>
      <td data-th="<?= $block->escapeHtmlAttr(__('Order Total')) ?>" class="font-weight-light total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
      <td data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>" class="font-weight-light status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
      <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="font-weight-light actions">
       <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
        <span><?= $block->escapeHtml(__('View Order')) ?></span>
       </a>
       <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
       <a href="#" data-post='<?= /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)->getPostData($block->getReorderUrl($_order))?>' class="ml-2 action order">
        <span><?= $block->escapeHtml(__('Reorder')) ?></span>
       </a>
       <?php endif ?>
      </td>
     </tr>
     <?php endforeach; ?>
    </tbody>
    
   </table>
   
  </div>
  
  <?php else : ?>
  <div class="font-weight-light mb-3 message info empty">
   <span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span>
  </div>
  <?php endif; ?>
  
 </div>
</div>
