<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>

<form class="form minisearch my-2 my-md-0 d-flex" id="search_mini_form" action="<?= $block->escapeUrl($helper->getResultUrl()) ?>" method="get">

 <input
  id="search"
  class="form-control d-inline-block font-weight-light"
  type="text"
  name="<?= $block->escapeHtmlAttr($helper->getQueryParamName()) ?>"
  value="<?= $block->escapeHtmlAttr($helper->getEscapedQueryText()) ?>"
  placeholder="<?= $block->escapeHtmlAttr(__('Search entire store here...')) ?>"
  maxlength="<?= $block->escapeHtmlAttr($helper->getMaxQueryLength()) ?>">

 <button type="submit" title="<?= $block->escapeHtmlAttr(__('Search')) ?>" class="search btn btn-transparent text-dark font-weight-light d-inline-block my-0" aria-label="Search">
  <span class="text-hide d-none">
   <?= $block->escapeHtml(__('Search')) ?>
  </span>
  <i class="fas fa-search"></i>
 </button>

</form>
