<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>

<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>

<?php

 $_productCollection = $block->getLoadedProductCollection();
 $_helper = $this->helper(Magento\Catalog\Helper\Output::class);

?>

<?php if (!$_productCollection->count()) :?>

 <div class="message info empty">
  <div class="font-weight-light"><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
 </div>

<?php else :?>

 <?= $block->getToolbarHtml() ?>
 
 <?= $block->getAdditionalHtml() ?>
 
 <?php
 
  if ($block->getMode() == 'grid') {
      
   $viewMode = 'grid';
   $rowMode = '';
   $boxMode = 'col-6 col-md-4 pb-4';
   $imageMode = '';
   $contentMode = '';
   $imageDisplayArea = 'category_page_grid';
   $showDescription = false;
   $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

  } else {
      
   $viewMode = 'list';
   $rowMode = 'row';
   $boxMode = 'col-12 pb-4';
   $imageMode = 'col-4';
   $contentMode = 'col';
   $imageDisplayArea = 'category_page_list';
   $showDescription = true;
   $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;

  }
  
  /**
  * Position for actions regarding image size changing in vde if needed
  */
  
  $pos = $block->getPositioned();
  
 ?>

 <div class="products-wrapper row">
 
  <div class="products-inner <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?> col-12">
 
   <ol class="products list items product-items row list-unstyled mb-0 py-3">
   
    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
    <?php foreach ($_productCollection as $_product) :?>
    <li class="item product product-item <?= $boxMode; ?>">
     <div class="product-item-info <?= $rowMode ?>" data-container="product-<?= /* @noEscape */ $viewMode ?>">

     <?php

     $productImage = $block->getImage($_product, $imageDisplayArea);

     if ($pos != null) {
      $position = ' style="left:' . $productImage->getWidth() . 'px;' . 'top:' . $productImage->getHeight() . 'px;"';
     }

     ?>
    
      <?php // Product Image ?>
    
      <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="<?= $imageMode ?> product-photo product-item-photo d-block overflow-hidden" tabindex="-1">
       <?= $productImage->toHtml() ?>
      </a>
     
      <div class="<?= $contentMode ?> product-details product-item-details my-3">

       <?php
        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
       ?>
      
       <h2 class="product-name product-item-name h6 font-weight-normal mb-2">
        <a class="product-item-link text-dark" href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
         <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
        </a>
       </h2>
      
       <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>

       <?= /* @noEscape */ $block->getProductPrice($_product) ?> 

       <?php if ($_product->isAvailable()) :?>
        <?= $block->getProductDetailsHtml($_product) ?>
       <?php endif; ?>
      
       <div class="product-item-inner">
        <div class="product-actions product-item-actions d-flex align-items-center my-3"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>

         <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
        
          <?php if ($_product->isSaleable()) :?>
         
          <?php $postParams = $block->getAddToCartPostParams($_product); ?>
         
          <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
           <input type="hidden" name="product" value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
           <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
           <?= $block->getBlockHtml('formkey') ?>
           <button type="submit" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class=" action tocart primary btn btn-primary mr-2 rounded-0 font-weight-light">
            <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
           </button>
          </form>
         
          <?php else :?>
         
          <?php if ($_product->isAvailable()) :?>
          <div class="stock available">
           <span><?= $block->escapeHtml(__('In stock')) ?></span>
          </div>
          <?php else :?>
          <div class="stock unavailable">
           <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
          </div>
          <?php endif; ?>
          
          <?php endif; ?>
         </div>
        
         <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>>
          <?php if ($addToBlock = $block->getChildBlock('addto')) :?>
           <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
          <?php endif; ?>
         </div>
        
        </div>
       
        <?php if ($showDescription) :?>
        <div class="product-description product-item-description">
       
         <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
         <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" title="<?= /* @noEscape */ $_productNameStripped ?>" class="action more">
          <?= $block->escapeHtml(__('Learn More')) ?>
         </a>

        </div>
        <?php endif; ?>
       
       </div>

      </div>
     
     </div>
    </li>
    <?php endforeach; ?>
   
   </ol>
  
  </div>

 </div>
 
 <?= $block->getToolbarHtml() ?>
 
 <?php if (!$block->isRedirectToCartEnabled()) :?>
 <script type="text/x-magento-init">
  {
   "[data-role=tocart-form], .form.map.checkout": {
    "catalogAddToCart": {
     "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
    }
   }
  }
 </script>
 <?php endif; ?>

<?php endif; ?>
