<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>

<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
?>

<?php if ($_additional = $block->getAdditionalData()) :?>
<div class="table-responsive table-borderless">
 <table class="table">
  <tbody>
   <?php foreach ($_additional as $_data) :?>
   <tr>
    <th class="col-auto font-weight-normal p-2 label" scope="row">
     <?= $block->escapeHtml($_data['label']) ?>
    </th>
    <td class="col font-weight-light p-2 data" data-th="<?= $block->escapeHtmlAttr($_data['label']) ?>">
     <?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>
    </td>
   </tr>
   <?php endforeach; ?>
  </tbody>
 </table>
</div>
<?php endif;?>
