<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>

<ul class="nav d-inline-block">

 <?php foreach ($filterItems as $filterItem) : ?>
 <li class="nav-item">

  <?php if ($filterItem->getCount() > 0) : ?>

  <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>" class="nav-link text-dark font-weight-light px-0 py-1">

   <?= /* @noEscape */ $filterItem->getLabel() ?>

   <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
   <span class="count">
    (<?= /* @noEscape */ (int)$filterItem->getCount() ?>)
    <span class="filter-count-label d-none">
    <?php if ($filterItem->getCount() == 1) :?>
     <?= $block->escapeHtml(__('item')) ?>
    <?php else : ?>
     <?= $block->escapeHtml(__('item')) ?>
    <?php  endif;?>
    </span>
   </span>
   <?php endif; ?>

  </a>

  <?php else :?>

   <?= /* @noEscape */ $filterItem->getLabel() ?>

   <?php if ($this->helper(\Magento\Catalog\Helper\Data::class)->shouldDisplayProductCountOnLayer()) : ?>
   <span class="count">
    (<?= /* @noEscape */ (int)$filterItem->getCount() ?>)
    <span class="filter-count-label d-none">
    <?php if ($filterItem->getCount() == 1) : ?>
     <?= $block->escapeHtml(__('items')) ?>
    <?php else : ?>
     <?= $block->escapeHtml(__('items')) ?>
    <?php endif;?>
    </span>
   </span>
   <?php endif; ?>
   
  <?php endif; ?>

 </li>
 <?php endforeach; ?>

</ul>