<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation state
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\State
 */
?>
<?php $_filters = $block->getActiveFilters() ?>

<?php if (!empty($_filters)) : ?>
<div class="filter-current">

 <h2 role="heading" aria-level="2" class="font-weight-light h5 mb-4 filter-current-subtitle">
  <?= $block->escapeHtml(__('Now Shopping by')) ?>
 </h2>
 
 <ol class="nav d-inline-block">
 
  <?php foreach ($_filters as $_filter) : ?>
  <li class="nav-item mb-2">

   <span class="d-block filter-label"><?= $block->escapeHtml(__($_filter->getName())) ?>:</span>
   <span class="d-block font-weight-light filter-value mb-1"><?= $block->escapeHtml($block->stripTags($_filter->getLabel())) ?></span>
   
   <?php
   
    $clearLinkUrl = $_filter->getClearLinkUrl();
    $currentFilterName = $block->escapeHtmlAttr(__($_filter->getName()) . " " . $block->stripTags($_filter->getLabel()));
    
    if ($clearLinkUrl) :
    
   ?>
   
   <a class="font-weight-light previous" href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>" title="<?= $block->escapeHtmlAttr(__('Previous')) ?>">
    <span><?= $block->escapeHtml(__('Previous')) ?></span>
   </a>
   
   <a class="font-weight-light remove" title="<?= $block->escapeHtmlAttr($_filter->getFilter()->getClearLinkText()) ?>" href="<?= $block->escapeUrl($clearLinkUrl) ?>">
    <span><?= $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
   </a>
   
   <?php else : ?>
   <a class="font-weight-light remove" href="<?= $block->escapeUrl($_filter->getRemoveUrl()) ?>" title="<?= /* @noEscape */ $block->escapeHtmlAttr(__('Remove')) . " " . $currentFilterName ?>">
    <span><?= $block->escapeHtml(__('Remove')) ?></span>
   </a>
   <?php endif; ?>
   
  </li>
  <?php endforeach; ?>
  
 </ol>

</div>
<?php endif; ?>
