<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>

<?php if ($block->getRegistration()->isAllowed()) : ?>
<div class="block block-new-customer">
    
 <h2 role="heading" aria-level="2" class="block-title font-weight-light h4 mb-4 pb-3 border-bottom">
  <span id="block-new-customer-heading" aria-level="2"><?= $block->escapeHtml(__('New Customers')) ?></span>
 </h2>
 
 <div class="block-content font-weight-light" aria-labelledby="block-new-customer-heading">
  <p>
   <?= $block->escapeHtml(__('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.')) ?>
  </p>
  <div class="actions-toolbar">
   <div class="primary">
    <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create primary btn btn-primary font-weight-light">
     <span><?= $block->escapeHtml(__('Create an Account')) ?></span>
    </a>
   </div>
  </div>
 </div>

</div>
<?php endif; ?>
