<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Store\Block\Switcher $block */
?>
<?php if (count($block->getStores())>1) : ?>

<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $block->escapeHtmlAttr($id) ?>">
 
 <span class="label switcher-label text-hide d-none"><?= $block->escapeHtml(__('Language')) ?></span>

 <ul class="navbar-nav">
  <li class="actions options switcher-options nav-item dropdown">

   <a id="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>" class="view-<?= $block->escapeHtml($block->getCurrentStoreCode()) ?> nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
    <span><?= $block->escapeHtml($block->getStoreName()) ?></span>
   </a>

   <div class="dropdown-menu dropdown-menu-right" aria-labelledby="switcher-language-trigger<?= $block->escapeHtmlAttr($id) ?>">
    <?php foreach ($block->getStores() as $_lang) : ?>
    <?php if ($_lang->getId() != $block->getCurrentStoreId()) : ?>
    <a class="view-<?= $block->escapeHtml($_lang->getCode()) ?> switcher-option dropdown-item font-weight-light px-3 py-1" href="<?= $block->escapeUrl($block->getViewModel()->getTargetStoreRedirectUrl($_lang)) ?>">
     <?= $block->escapeHtml($_lang->getName()) ?>
    </a>
    <?php endif; ?>
    <?php endforeach; ?>
   </div>
   
  </li>
 </ul>

</div>
<?php endif; ?>
