<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="bugs mb-4 my-lg-3 text-white text-center text-lg-right">
 <small><?= $block->escapeHtml(__('Help Us Keep Magento Healthy')) ?>
  <a href="http://www.magentocommerce.com/bug-tracking" target="_blank" title="<?= $block->escapeHtmlAttr(__('Report All Bugs')) ?>" class="text-white"><?= $block->escapeHtml(__('Report All Bugs')) ?></a>
 </small>
</div>
