<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>
<?php if ($block->getCollection()->getSize()) : ?>

<?php if ($block->getUseContainer()) : ?>
<div class="pager d-flex align-items-center">
<?php endif ?>
 
 <?php if ($block->getShowAmounts()) : ?>
 <div class="toolbar-amount my-3 ml-auto order-2">
  
  <span class="toolbar-number">
   <?php if ($block->getLastPageNum()>1) : ?>
    <?= $block->escapeHtml(__('Items %1 to %2 of %3 total', $block->getFirstNum(), $block->getLastNum(), $block->getTotalNum())) ?>
   <?php elseif ($block->getTotalNum() == 1) : ?>
    <?= $block->escapeHtml(__('%1 Item', $block->getTotalNum())) ?>
   <?php else : ?>
    <?= $block->escapeHtml(__('%1 Item(s)', $block->getTotalNum())) ?>
   <?php endif; ?>
  </span>
  
 </div>
 <?php endif ?>

 <?php if ($block->getLastPageNum()>1) : ?>
 <nav aria-label="Page Items" aria-labelledby="paging-label">
  <ul class="pagination items pages-items my-4">

   <?php if (!$block->isFirstPage()) : ?>
   <li class="page-item pages-item-previous">
    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : ''; ?>
    <a class="<?= $block->escapeHtmlAttr($text ? 'link ' : 'action ') ?> previous page-link rounded-0 text-dark font-weight-light" href="<?= $block->escapeUrl($block->getPreviousPageUrl()) ?>" title="<?= $block->escapeHtmlAttr($text ? $text : __('Previous')) ?>"><?= $block->escapeHtml($text ? $text : __('Previous')) ?></a>
   </li>
   <?php endif;?>

   <?php if ($block->canShowFirst()) : ?>
   <li class="page-item">
    <a class="page first page-link rounded-0 text-dark font-weight-light" href="<?= $block->escapeUrl($block->getFirstPageUrl()) ?>">1</a>
   </li>
   <?php endif;?>

   <?php if ($block->canShowPreviousJump()) : ?>
   <li class="page-item">
    <a class="page previous jump page-link rounded-0 text-dark font-weight-light" href="<?= $block->escapeUrl($block->getPreviousJumpUrl()) ?>">...</a>
   </li>
   <?php endif;?>

   <?php foreach ($block->getFramePages() as $_page) : ?>
    <?php if ($block->isPageCurrent($_page)) : ?>
    <li class="page-item disabled current">
     <span class="page page-link rounded-0 font-weight-bold bg-light"><?= $block->escapeHtml($_page) ?></span>
    </li>
    <?php else : ?>
    <li class="page-item">
     <a class="page page-link rounded-0 text-dark font-weight-light" href="<?= $block->escapeUrl($block->getPageUrl($_page)) ?>"><?= $block->escapeHtml($_page) ?></a>
    </li>
    <?php endif;?>
   <?php endforeach;?>

   <?php if ($block->canShowNextJump()) : ?>
   <li class="page-item">
    <a class="page next jump page-link rounded-0 text-dark font-weight-light" href="<?= $block->escapeUrl($block->getNextJumpUrl()) ?>">...</a>
   </li>
   <?php endif;?>

   <?php if ($block->canShowLast()) : ?>
   <li class="page-item">
    <a class="page last page-link rounded-0 text-dark font-weight-light" href="<?= $block->escapeUrl($block->getLastPageUrl()) ?>"><?= $block->escapeHtml($block->getLastPageNum()) ?></a>
   </li>
   <?php endif;?>

   <?php if (!$block->isLastPage()) : ?>
   <li class="page-item pages-item-next">
    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
    <a class="<?= /* @noEscape */ $text ? 'link ' : 'action ' ?> next page-link rounded-0 text-dark font-weight-light" href="<?= $block->escapeUrl($block->getNextPageUrl()) ?>" title="<?= $block->escapeHtmlAttr($text ? $text : __('Next')) ?>">
     <?= $block->escapeHtml($text ? $text : __('Next')) ?>
    </a>
   </li>
   <?php endif;?>

  </ul>
 </nav>
 <?php endif; ?>
 
 <?php if ($block->isShowPerPage()) : ?>
 <div class="limiter my-3 order-1">

  <div class="d-flex align-items-center">

   <span class="limiter-label font-weight-normal"><?= $block->escapeHtml(__('Show')) ?></span>

   <div class="ml-2">
    <select id="limiter" data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options form-control font-weight-light p-1">
     <?php foreach ($block->getAvailableLimit() as $_key => $_limit) : ?>
     <option value="<?= $block->escapeHtmlAttr($block->getLimitUrl($_key)) ?>" <?php if ($block->isLimitCurrent($_key)) : ?>selected="selected"<?php endif ?>>
     <?= $block->escapeHtml($_limit) ?>
     </option>
     <?php endforeach; ?>
    </select>
   </div>

   <div class="limiter-text font-weight-light ml-2"><?= $block->escapeHtml(__('per page')) ?></div>

  </div>

 </div>
 <?php endif ?>
 
<?php if ($block->getUseContainer()) : ?>
</div>
<?php endif ?>

<?php endif ?>
