<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block Magento\Framework\View\Element\Template */
?>
<li class="item link compare nav-item" data-bind="scope: 'compareProducts'" data-role="compare-products-link">

 <a class="action compare d-none nav-link font-weight-light text-white px-2" title="<?= $block->escapeHtmlAttr(__('Compare Products')) ?>" data-bind="attr: {'href': compareProducts().listUrl}, css: {'d-none': !compareProducts().count}" >
  <?= $block->escapeHtml(__('Compare Products')) ?>
  <span class="counter qty" data-bind="text: compareProducts().countCaption"></span>
 </a>

</li>

<script type="text/x-magento-init">
 {
  "[data-role=compare-products-link]": {
   "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
  }
 }
</script>
