<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/* @var $block \Magento\Framework\View\Element\Template */
?>
<div class="compare" data-bind="scope: 'compareProducts'" data-role="compare-products-sidebar">

 <h2 role="heading" aria-level="2" class="font-weight-light h5 mb-4 title">
  <span id="compare-heading" aria-level="2"><?= $block->escapeHtml(__('Compare Products')) ?></span>
  <span class="counter qty no-display" data-bind="text: '(' + compareProducts().countCaption + ')', css: {'no-display': !compareProducts().count}"></span>
 </h2>
 
 <!-- ko if: compareProducts().count -->
 <div class="content no-display" aria-labelledby="compare-heading" data-bind="css: {'no-display': !compareProducts().count}">
 
  <ol id="compare-items" class="nav d-inline-block product-items product-items-names" data-bind="foreach: compareProducts().items">
   <li class="nav-item mb-2 product-item">

    <input type="hidden" class="compare-item-id" data-bind="value: id"/>

    <span class="d-block product-item-name">
     <a data-bind="attr: {href: product_url}, html: name" class="text-dark font-weight-light mb-1 product-item-link"></a>
    </span>
    
    <a href="#" data-bind="attr: {'data-post': remove_url}" title="<?= $block->escapeHtmlAttr(__('Remove')) ?>" class="font-weight-light delete">
     <span><?= $block->escapeHtml(__('Remove')) ?></span>
    </a>

   </li>
  </ol>
  
  <div class="actions-toolbar">

   <div class="primary">
    <a data-bind="attr: {'href': compareProducts().listUrl}" class="d-inline-block mb-2 compare">
     <span><?= $block->escapeHtml(__('Compare')) ?></span>
    </a>
   </div>
   
   <div class="secondary">
    <a id="compare-clear-all" href="#" class="d-inline-block mb-3 clear" data-post="<?=$block->escapeHtml($this->helper(Magento\Catalog\Helper\Product\Compare::class)->getPostDataClearList()) ?>">
     <span><?= $block->escapeHtml(__('Clear All')) ?></span>
    </a>
   </div>
   
  </div>
  
 </div>
 <!-- /ko -->
 
 <!-- ko ifnot: compareProducts().count -->
 <div class="empty font-weight-light mb-4">
  <?= $block->escapeHtml(__('You have no items to compare.')) ?>
 </div>
 <!-- /ko -->
 
</div>

<script type="text/x-magento-init">
 {"[data-role=compare-products-sidebar]": {"Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>}}
</script>
