<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */

// phpcs:disable Magento2.Security.IncludeFile.FoundIncludeFile
// phpcs:disable PSR2.Methods.FunctionCallSignature.SpaceBeforeOpenBracket
?>
<?php if ($block->getCollection()->getSize()) :?>

 <?php $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
  $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
 ?>
 
 <div class="row align-items-center border-top mx-0 toolbar toolbar-products-top" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>

  <div class="col px-0">

   <?php if ($block->isExpanded()) :?>
    <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
   <?php endif; ?>
   
  </div>
  
  <div class="col-auto px-0">
  
   <?php if ($block->isExpanded()) :?>
    <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
   <?php endif; ?>
   
  </div>

 </div>

 <div class="row align-items-center border-top mx-0 toolbar toolbar-products-middle">
 
  <div class="col px-0">
   <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
  </div>

  <div class="col-auto px-0">
   <?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
  </div>

 </div>

 <div class="row align-items-center toolbar toolbar-products-bottom">
 
  <div class="col-auto">
   <?= $block->getPagerHtml() ?>
  </div>
 
 </div>

<?php endif ?>
