<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Edit $block */
?>
<form class="form form-edit-account" action="<?= $block->escapeUrl($block->getUrl('customer/account/editPost')) ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>" autocomplete="off">

 <div class="row">

  <div class="col-lg-6">
   <fieldset class="mb-3 fieldset info">

    <?= $block->getBlockHtml('formkey') ?>

    <h2 role="heading" aria-level="2" class="font-weight-light h5 mb-4 pb-3 border-bottom title">
     <span><?= $block->escapeHtml(__('Account Information')) ?></span>
    </h2>
  
    <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)->setObject($block->getCustomer())->toHtml() ?>
  
    <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
    <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
    <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
  
    <?php if ($_dob->isEnabled()) : ?>
    <?= $_dob->setDate($block->getCustomer()->getDob())->toHtml() ?>
    <?php endif ?>
  
    <?php if ($_taxvat->isEnabled()) : ?>
    <?= $_taxvat->setTaxvat($block->getCustomer()->getTaxvat())->toHtml() ?>
    <?php endif ?>
  
    <?php if ($_gender->isEnabled()) : ?>
    <?= $_gender->setGender($block->getCustomer()->getGender())->toHtml() ?>
    <?php endif ?>
  
    <div class="form-group font-weight-light mb-2 field choice">
     <input type="checkbox" name="change_email" id="change-email" data-role="change-email" value="1" title="<?= $block->escapeHtmlAttr(__('Change Email')) ?>" class="checkbox" />
     <label class="label m-0" for="change-email"><span><?= $block->escapeHtml(__('Change Email')) ?></span></label>
    </div>
  
    <div class="form-group font-weight-light mb-2 field choice">
     <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?= $block->escapeHtmlAttr(__('Change Password')) ?>"<?php if ($block->getChangePassword()) : ?> checked="checked"<?php endif; ?> class="checkbox" />
     <label class="label m-0" for="change-password"><span><?= $block->escapeHtml(__('Change Password')) ?></span></label>
    </div>
  
   </fieldset>
  </div>
 
  <div class="col-lg-6">
   <fieldset class="fieldset password" data-container="change-email-password">

    <h2 role="heading" aria-level="2" class="font-weight-light h5 mb-4 pb-3 border-bottom title">
     <span data-title="change-email-password"><?= $block->escapeHtml(__('Change Email and Password')) ?></span>
    </h2>
  
    <div class="form-group font-weight-light field email required" data-container="change-email">
     <label class="label" for="email">
      <span><?= $block->escapeHtml(__('Email')) ?></span>
     </label>
     <div class="control">
      <input type="email" name="email" id="email" autocomplete="email" data-input="change-email" value="<?= $block->escapeHtmlAttr($block->getCustomer()->getEmail()) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="form-control input-text" data-validate="{required:true, 'validate-email':true}" />
     </div>
    </div>
  
    <div class="form-group font-weight-light field password current required">
     <label class="label" for="current-password"><span><?= $block->escapeHtml(__('Current Password')) ?></span></label>
     <div class="control">
      <input type="password" class="form-control input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
     </div>
    </div>
  
    <div class="form-group font-weight-light field new password required" data-container="new-password">
     <label class="label" for="password">
      <span><?= $block->escapeHtml(__('New Password')) ?></span>
     </label>
     <div class="control">
      <input type="password" class="form-control input-text" name="password" id="password" data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>" data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>" data-input="new-password" data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off" />
      <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
       <div id="password-strength-meter" class="password-strength-meter">
        <?= $block->escapeHtml(__('Password Strength')) ?>:
        <span id="password-strength-meter-label" data-role="password-strength-meter-label">
        <?= $block->escapeHtml(__('No Password')) ?>
        </span>
       </div>
      </div>
     </div>
    </div>
  
    <div class="form-group font-weight-light field confirm password required" data-container="confirm-password">
     <label class="label" for="password-confirmation">
      <span><?= $block->escapeHtml(__('Confirm New Password')) ?></span>
     </label>
     <div class="control">
      <input type="password" class="form-control input-text" name="password_confirmation" id="password-confirmation" data-input="confirm-password" autocomplete="off" />
     </div>
    </div>
  
   </fieldset>
  </div>

 </div>

 <?= $block->getChildHtml('form_additional_info') ?>

 <div class="actions-toolbar">
  <div class="primary">
   <button type="submit" class="btn btn-primary font-weight-light mb-3 action save primary" title="<?= $block->escapeHtmlAttr(__('Save')) ?>">
    <span><?= $block->escapeHtml(__('Save')) ?></span>
   </button>
  </div>
  <div class="secondary">
   <a class="text-dark font-weight-light action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
    <span><?= $block->escapeHtml(__('Go back')) ?></span>
   </a>
  </div>
 </div>

</form>

<script>
 require([
  "jquery",
  "mage/mage"
 ], function($){
     
  var dataForm = $('#form-validate');
  var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;
  
  dataForm.mage('validation', {
   <?php if ($_dob->isEnabled()) : ?>
   errorPlacement: function(error, element) {
    if (element.prop('id').search('full') !== -1) {
     var dobElement = $(element).parents('.customer-dob'),
         errorClass = error.prop('class');
         error.insertAfter(element.parent());
     dobElement.find('.validate-custom').addClass(errorClass).after('<div class="' + errorClass + '"></div>');
    } else {
     error.insertAfter(element);
    }
   },
   ignore: ':hidden:not(' + ignore + ')'
   <?php else : ?>
   ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
   <?php endif ?>
  });
  
 });
</script>

<script type="text/x-magento-init">
 {
  "[data-role=change-email], [data-role=change-password]": {
   "changeEmailPassword": {
    "titleChangeEmail": "<?= $block->escapeJs($block->escapeHtml(__('Change Email'))) ?>",
    "titleChangePassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Password'))) ?>",
    "titleChangeEmailAndPassword": "<?= $block->escapeJs($block->escapeHtml(__('Change Email and Password'))) ?>"
   }
  },
  "[data-container=new-password]": {
   "passwordStrengthIndicator": {
    "formSelector": "form.form-edit-account"
   }
  }
 }
</script>
