<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>

<form class="form password forget font-weight-light" action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>" method="post" id="form-validate" data-mage-init='{"validation":{}}'>

 <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">

  <div class="form-row">
   <div class="field note col-12 form-group">
    <?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?>
   </div>
  </div>

  <div class="form-row">
   <div class="field email required col-lg-8 col-xl-9 form-group">
    <label for="email_address" class="label">
     <span><?= $block->escapeHtml(__('Email')) ?></span>
    </label>
    <div class="control">
     <input type="email" name="email" alt="email" id="email_address" class="input-text form-control" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
    </div>
   </div>
  </div>

  <div class="form-row">
   <div class="col-lg-8 col-xl-9 form-group">
    <?= $block->getChildHtml('form_additional_info') ?>
   </div>
  </div>

 </fieldset>
 
 <div class="actions-toolbar">

  <div class="primary">
   <button type="submit" class="action submit primary btn btn-primary font-weight-light mb-3">
    <span><?= $block->escapeHtml(__('Reset My Password')) ?></span>
   </button>
  </div>

  <div class="secondary">
   <a class="action back text-dark font-weight-light" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>">
    <span><?= $block->escapeHtml(__('Go back')) ?></span>
   </a>
  </div>

 </div>

</form>
