<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login $block */
?>

<div class="customer-login">
    
 <h2 role="heading" aria-level="2" id="customer-heading" class="font-weight-light h5 mb-3 pb-3 border-bottom title">
  <span aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></span>
 </h2>
 
 <div class="font-weight-light content" aria-labelledby="customer-login-heading">

  <form class="mb-4 form form-login" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="login-form" data-mage-init='{"validation":{}}'>
  
   <?= $block->getBlockHtml('formkey') ?>

   <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">

    <div class="form-row">
     <div class="col-12 form-group field note">
      <?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?>
     </div>
    </div>

    <div class="form-row">
     <div class="col-lg-9 form-group field email required">
      <label class="label" for="email">
       <span><?= $block->escapeHtml(__('Email')) ?></span>
      </label>
      <div class="control">
       <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="form-control input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
      </div>
     </div>
    </div>

    <div class="form-row">
     <div class="col-lg-9 form-group field password required">

      <label for="pass" class="label">
       <span><?= $block->escapeHtml(__('Password')) ?></span>
      </label>
     
      <div class="control">
       <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="form-control input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
      </div>

     </div>
    </div>
    
    <div class="form-row">
     <div class="col-lg-9">
      <?= $block->getChildHtml('form_additional_info') ?>
     </div>
    </div>

   </fieldset>

   <div class="actions-toolbar">
    <div class="primary">
     <button type="submit" class="btn btn-primary font-weight-light mb-3 action login primary" name="send" id="send2">
      <span><?= $block->escapeHtml(__('Sign In')) ?></span>
     </button>
    </div>
    <div class="secondary">
     <a class="text-dark action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>">
      <span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span>
     </a>
    </div>
   </div>

  </form>

 </div>
</div>

