<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="block block-dashboard-addresses mb-4">

 <h2 role="heading" aria-level="2" class="block-title font-weight-light h5 mb-4 pb-3 border-bottom">
  <span><?= $block->escapeHtml(__('Address Book')) ?></span>
  <a class="action edit font-weight-light h6 ml-2" href="<?= $block->escapeUrl($block->getAddressBookUrl()) ?>">
   <span><?= $block->escapeHtml(__('Manage Addresses')) ?></span>
  </a>
 </h2>
 
 <div class="block-content row">

  <div class="box box-billing-address col-md-6">

   <h3 class="box-title font-weight-normal h6">
    <span><?= $block->escapeHtml(__('Default Billing Address')) ?></span>
   </h3>
   
   <div class="box-content font-weight-light mb-2">
    <address>
     <?= $block->getPrimaryBillingAddressHtml() ?>
    </address>
   </div>
   
   <div class="box-actions mb-3">
    <a class="action edit font-weight-light" href="<?= $block->escapeUrl($block->getPrimaryBillingAddressEditUrl()) ?>" data-ui-id="default-billing-edit-link">
     <span><?= $block->escapeHtml(__('Edit Address')) ?></span>
    </a>
   </div>
   
  </div>
  
  <div class="box box-shipping-address col-md-6">
  
   <h3 class="box-title font-weight-normal h6">
    <span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span>
   </h3>
   
   <div class="box-content font-weight-light mb-2">
    <address>
     <?= $block->getPrimaryShippingAddressHtml() ?>
    </address>
   </div>
   
   <div class="box-actions mb-3">
    <a class="action edit font-weight-light" href="<?= $block->escapeUrl($block->getPrimaryShippingAddressEditUrl()) ?>" data-ui-id="default-shipping-edit-link">
     <span><?= $block->escapeHtml(__('Edit Address')) ?></span>
    </a>
   </div>
   
  </div>
 
 </div>

</div>
