<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="block block-dashboard-info mb-4">

 <h2 role="heading" aria-level="2" class="block-title font-weight-light h5 mb-4 pb-3 border-bottom">
  <span><?= $block->escapeHtml(__('Account Information')) ?></span>
 </h2>

 <div class="block-content row">
 
  <div class="box box-information col-md-6">

   <h3 class="box-title font-weight-normal h6">
    <span><?= $block->escapeHtml(__('Contact Information')) ?></span>
   </h3>
   
   <div class="box-content font-weight-light mb-2">
    <div>
     <?= $block->escapeHtml($block->getName()) ?>
    </div>
    <div>
     <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?>
    </div>
    <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
   </div>
   
   <div class="box-actions mb-3">

    <a class="action edit font-weight-light" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
     <span><?= $block->escapeHtml(__('Edit')) ?></span>
    </a>
    
    <a href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="action change-password font-weight-light ml-2">
     <?= $block->escapeHtml(__('Change Password')) ?>
    </a>
    
   </div>
   
  </div>
  
  <?php if ($block->isNewsletterEnabled()) : ?>
  <div class="box box-newsletter col-md-6">
  
   <h3 class="box-title font-weight-normal h6">
    <span><?= $block->escapeHtml(__('Newsletters')) ?></span>
   </h3>
   
   <div class="box-content font-weight-light mb-2">
    <p>
     <?php if ($block->getIsSubscribed()) : ?>
     <?= $block->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
     <?php else : ?>
     <?= $block->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
     <?php endif; ?>
    </p>
   </div>
   
   <div class="box-actions mb-3">
    <a class="action edit font-weight-light" href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
   </div>
   
  </div>
  <?php endif; ?>
  
 </div>

</div>
