<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="mb-4 dashboard-info">

 <h2 role="heading" aria-level="2" class="font-weight-light h5 mb-4 pb-3 border-bottom title">
  <span><?= $block->escapeHtml(__('Account Information')) ?></span>
 </h2>

 <div class="row content">
 
  <div class="col-md-6 box box-information">

   <h3 class="font-weight-normal h6 box-title">
    <span><?= $block->escapeHtml(__('Contact Information')) ?></span>
   </h3>
   
   <div class="font-weight-light mb-2 box-content">
    <div>
     <?= $block->escapeHtml($block->getName()) ?>
    </div>
    <div>
     <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?>
    </div>
    <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?>
   </div>
   
   <div class="mb-3 box-actions">

    <a class="font-weight-light action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
     <span><?= $block->escapeHtml(__('Edit')) ?></span>
    </a>
    
    <a href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="font-weight-light ml-2 action change-password">
     <?= $block->escapeHtml(__('Change Password')) ?>
    </a>
    
   </div>
   
  </div>
  
  <?php if ($block->isNewsletterEnabled()) : ?>
  <div class="col-md-6 box box-newsletter">
  
   <h3 class="font-weight-normal h6 box-title">
    <span><?= $block->escapeHtml(__('Newsletters')) ?></span>
   </h3>
   
   <div class="font-weight-light mb-2 box-content">
    <p>
     <?php if ($block->getIsSubscribed()) : ?>
     <?= $block->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
     <?php else : ?>
     <?= $block->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
     <?php endif; ?>
    </p>
   </div>
   
   <div class="mb-3 box-actions">
    <a class="font-weight-light action edit" href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
   </div>
   
  </div>
  <?php endif; ?>
  
 </div>

</div>
