
<ul class="nav nav-tabs" id="myTab" role="tablist">
 <li class="nav-item">
  <a class="nav-link active text-dark font-weight-light rounded-0 bg-transparent" id="settings-menu-tab" data-toggle="tab" href="#settings-menu" role="tab" aria-controls="settings-menu" aria-selected="true"><?= __('Menu') ?></a>
 </li>
 <li class="nav-item">
  <a class="nav-link text-dark font-weight-light rounded-0 bg-transparent" id="settings-account-tab" data-toggle="tab" href="#settings-account" role="tab" aria-controls="settings-account" aria-selected="false"><?= __('Account') ?></a>
 </li>
 <li class="nav-item">
  <a class="nav-link text-dark font-weight-light rounded-0 bg-transparent" id="settings-settings-tab" data-toggle="tab" href="#settings-settings" role="tab" aria-controls="settings-settings" aria-selected="false"><?= __('Settings') ?></a>
 </li>
</ul>

<div class="tab-content" id="myTabContent">
 <div class="tab-pane fade show active" id="settings-menu" role="tabpanel" aria-labelledby="settings-menu-tab">
  <div class="p-2">
  <?= $this->getLayout()->createBlock('SageKit\Bootstrap4CategoryMenu\Block\CategoryMenu')->setTemplate('SageKit_Bootstrap4CategoryMenu::html/category-menu.phtml')->toHtml(); ?>
  </div>
 </div>
 <div class="tab-pane fade" id="settings-account" role="tabpanel" aria-labelledby="settings-account-tab">
  <div class="p-2">
   <ul class="navbar-nav">
    <?= $this->getLayout()->createBlock('Magento\Customer\Block\Account\AuthorizationLink')->setTemplate('Magento_Customer::account/link/authorization.phtml')->toHtml(); ?>
   </ul>
  </div>
 </div>
 <div class="tab-pane fade" id="settings-settings" role="tabpanel" aria-labelledby="settings-settings-tab">
  <div class="p-2">
  <?= $this->getLayout()->createBlock('Magento\Store\Block\Switcher')->setTemplate('Magento_Store::switch/languages.phtml')->toHtml(); ?>
  </div>
 </div>
</div>